### ISSUE TITLE
python -m GolemQ.cli --sub sina_l1 报错

### ISSUE THREAD

**Issue by godblessme111** [Rgveda/GolemQ#1]
完全按照readme文档操作 qa为docker版本 且手工升级过报错信息
在 repo 根目录下面，输入
python -m GolemQ.cli --sub sina_l1
报错
/usr/local/bin/python: Error while finding module specification for 'GolemQ.cli' (ModuleNotFoundError: No module named 'GolemQ')
输入cd ..
python -m GolemQ.cli --sub sina_l1
报错
you are using non-interactive mdoel quantaxis
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/GolemQ/cli/__main__.py", line 49, in <module>
    from GolemQ.GQUtil.symbol import (
  File "/root/GolemQ/GQUtil/__init__.py", line 29, in <module>
    import GolemQ.GQUtil.parameter as GQParameter
AttributeError: module 'GolemQ' has no attribute 'GQUtil'

**Comment by Rgveda** [comment]
cd GolemQ 
ls
看看有没有 GQUtil 目录

**Comment by Rgveda** [comment]
> 
> 
> 完全按照readme文档操作 qa为docker版本 且手工升级过报错信息
> 在 repo 根目录下面，输入
> python -m GolemQ.cli --sub sina_l1
> 报错
> /usr/local/bin/python: Error while finding module specification for 'GolemQ.cli' (ModuleNotFoundError: No module named 'GolemQ')
> 输入cd ..
> python -m GolemQ.cli --sub sina_l1
> 报错
> you are using non-interactive mdoel quantaxis
> Traceback (most recent call last):
> File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
> "**main**", mod_spec)
> File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
> exec(code, run_globals)
> File "/root/GolemQ/cli/**main**.py", line 49, in
> from GolemQ.GQUtil.symbol import (
> File "/root/GolemQ/GQUtil/**init**.py", line 29, in
> import GolemQ.GQUtil.parameter as GQParameter
> AttributeError: module 'GolemQ' has no attribute 'GQUtil'

cd GolemQ
ls
看看有没有 GQUtil 目录

**Comment by Rgveda** [comment]
> 
> 
> 完全按照readme文档操作 qa为docker版本 且手工升级过报错信息
> 在 repo 根目录下面，输入
> python -m GolemQ.cli --sub sina_l1
> 报错
> /usr/local/bin/python: Error while finding module specification for 'GolemQ.cli' (ModuleNotFoundError: No module named 'GolemQ')
> 输入cd ..
> python -m GolemQ.cli --sub sina_l1
> 报错
> you are using non-interactive mdoel quantaxis
> Traceback (most recent call last):
> File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
> "**main**", mod_spec)
> File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
> exec(code, run_globals)
> File "/root/GolemQ/cli/**main**.py", line 49, in
> from GolemQ.GQUtil.symbol import (
> File "/root/GolemQ/GQUtil/**init**.py", line 29, in
> import GolemQ.GQUtil.parameter as GQParameter
> AttributeError: module 'GolemQ' has no attribute 'GQUtil'

这个问题已经更新修正，执行 git pull / fetch 更新代码即可。
